# Generated by Django 6.0.3 on 2026-06-24 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('goal_type', models.CharField(choices=[('steps', 'Шаги'), ('duration', 'Минуты активности'), ('calories', 'Калории'), ('water', 'Вода'), ('custom', 'Своя цель')], max_length=20)),
                ('target_value', models.FloatField(help_text='Целевое значение')),
                ('current_value', models.FloatField(default=0.0, help_text='Текущий прогресс')),
                ('unit', models.CharField(default='шаги', max_length=20)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
