# Generated by Django 6.0.3 on 2026-06-24 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_type', models.CharField(choices=[('steps', 'Шаги'), ('water', 'Вода'), ('duration', 'Время тренировки'), ('calories', 'Калории')], max_length=20)),
                ('target_value', models.IntegerField()),
                ('current_value', models.IntegerField(default=0)),
                ('difficulty', models.CharField(choices=[('easy', 'Легкая'), ('medium', 'Средняя'), ('hard', 'Тяжелая'), ('extreme', 'Экстремальная')], default='medium', max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ежедневное задание',
                'verbose_name_plural': 'Ежедневные задания',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
